image: archlinux
packages:
  - nodejs
  - npm
sources:
  - https://git.sr.ht/~djlooop/ktleary.com
tasks:
  - setup: |
      cd invidi.link
      npm install
  - test: |
      cd invidi.link
      npm test


